# this is an intuitive implementation of the algorithm in order to understand the algorithm and what it does

In [1]:
import transformers

# Load the model and processor
model = transformers.CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = transformers.CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

config.json:   0%|          | 0.00/4.19k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/605M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/592 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/862k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

In [4]:
import PIL
# Load the images
images = [PIL.Image.open("dog.png")]
possible_classes = ["an image of a bird", "an image of a dog", "an image of a cat"]

In [7]:
import torch
# Perform the inference by giving the model the images and the text
with torch.no_grad():
    inputs = processor(text=possible_classes, images=images, return_tensors="pt", padding=True, truncation=True)
    outputs = model(**inputs)

In [8]:
dot_products_per_image = outputs.logits_per_image
dot_products_per_text = outputs.logits_per_text


In [15]:
# this is the dot product between the image and the text for each possible class(in the md document an image example is given)
# the dot product is a measure of similarity between the image and the text
print(dot_products_per_image, dot_products_per_text)

tensor([[21.3833, 28.4259, 22.6724]]) tensor([[21.3833],
        [28.4259],
        [22.6724]])


In [10]:
probabilities = dot_products_per_image.softmax(dim=1)
print(probabilities)

tensor([[8.7032e-04, 9.9597e-01, 3.1590e-03]])


In [11]:
# get the index of the most likely class
predicted_class_indices = probabilities.argmax(dim=1)
print(predicted_class_indices)

tensor([1])
